[workspace]
resolver = "2"
members = [
    "d10-core",
    "d10-codecs",
    "d10-ops",
    "d10",
    "d10-commands",
    "d10-cli",
    "d10-python",
]

[profile.dev]
opt-level = 1

[profile.release]
lto = true