[package]
name = "d10-codecs"
version = "0.1.0"
authors = ["Volker Ströbel <volkerstroebel@mysurdity.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
image = { version = "0.23", default-features = false, features = ["jpeg"] }
png = "0.16"
byteorder = "1.4"
d10-core = { path = "../d10-core" }