[package]
name = "d10-core"
version = "0.1.0"
authors = ["Volker Ströbel <volkerstroebel@mysurdity.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]

[dev-dependencies]
rand = "0.8"
